# Generated by Django 6.0.7 on 2026-08-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='is_uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resume',
            name='resume_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
