# Generated by Django 5.1.15 on 2026-08-07 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_resume_is_uploaded_resume_resume_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='template_id',
            field=models.CharField(blank=True, default='classic', max_length=50),
        ),
        migrations.AddField(
            model_name='resume',
            name='theme_color',
            field=models.CharField(blank=True, default='#2563eb', max_length=20),
        ),
    ]
