# Generated by Django 5.1.15 on 2026-08-07 07:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverLetter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Untitled Cover Letter', max_length=255)),
                ('job_title', models.CharField(blank=True, default='', max_length=255)),
                ('company_name', models.CharField(blank=True, default='', max_length=255)),
                ('recipient_name', models.CharField(blank=True, default='Hiring Manager', max_length=255)),
                ('tone', models.CharField(default='Professional', max_length=50)),
                ('job_description', models.TextField(blank=True, default='')),
                ('salutation', models.CharField(default='Dear Hiring Manager,', max_length=255)),
                ('body_paragraphs', models.JSONField(blank=True, default=list)),
                ('closing', models.CharField(default='Sincerely,', max_length=255)),
                ('template_id', models.CharField(blank=True, default='classic', max_length=50)),
                ('theme_color', models.CharField(blank=True, default='#2563eb', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover_letters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cover_letters',
                'ordering': ['-updated_at'],
            },
        ),
    ]
